# Generated by Django 2.1.1 on 2018-09-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180906_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='NUll', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(default='NUll', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='NUll', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='NUll', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='NUll', max_length=30),
        ),
    ]
