# Generated by Django 2.1.1 on 2018-09-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180906_1545'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='my_employee',
        ),
        migrations.AlterModelTable(
            name='student',
            table='my_student',
        ),
    ]
