# Generated by Django 2.1.1 on 2018-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180906_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='ename',
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='myapp_employee',
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
