# Generated by Django 2.1.1 on 2018-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180906_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='econtact',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='ename',
            field=models.CharField(default='NUll', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='NUll', max_length=20),
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
